#! /bin/sh
nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &
compton &
copyq &
/home/adith_pc/scripts/./polybarstart.sh &

xsetroot -cursor_name left_ptr &
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config window_gap           1
bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_width 1

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
